### ISSUE TITLE
Can't Log in

### ISSUE THREAD

**Issue by BaronosMS** [ZencashOfficial/arizen#160]
Hello,

I made an Arizen account and deposited couple of Zencash 

Yesterday i tried to log in everything was working great. Today i can't log in . It keeps saying that i have wrong password and username , which is not that case . Please let me know how i can take back my account . Thank you

**Comment by Tigger1** [comment]
Hello BaronosMS,

Thank you for your question.

Please, close the Arizen wallet, then start the Arizen wallet again and try to log in again. You have to be careful while writing the Username and Paasword. If you mess it, you can have problems to log in even though you write it correctly for the second time. If it doen't still work, restart computer, launch Arizen wallet and try to log in again (and be careful while typing ;-) )

If it doesn't help you, please, let me know.

Have a nice day :-)
Tigger

**Comment by BaronosMS** [comment]
Hello Tigger1,

So after countless times of spamming my password with copy paste Ctrl + V i managed to open it . But trust me this shit is scary . How come the same password to not go through the log in ? 

Is there any other way to access my wallet . like a passphrase or a backup document ? 

I just withdrew them to Bittrex till this is solved . THank you

Thanks for the quick reply i appreciate it .

**Comment by Tigger1** [comment]
Hello BaronosMS,

thank you for your feedback. I agree with you. We've still worked on the Arizen and tried to improve it. I'm very sorry for your inconvenience:-(

Your wallet can be saved as _*.uawd_ (uncrypted Arizen wallet database) or _*.awd_ (Arizen wallet database) file. You need to log in, then click on "File" and choose your option. It is shown on a picture below:

![save_as_uawd](https://user-images.githubusercontent.com/32774850/34246384-a7920b26-e62e-11e7-953e-88d218a2edbe.png)

It would be better to check out also [the short user manual](https://github.com/ZencashOfficial/arizen/releases/tag/v1.1.1) , it's **Arizen.v1.1.1.Wallet.User.Manual.pdf**.

If you need any other help, please, let me know.
I wish you Merry Christmas:-)
Tigger1

**Comment by dmjjmd** [comment]
Having the same problem here, I've yet to successfully get into the Arizen wallet, but will keep trying.  It doesn't tell me I have the wrong username or password, rather it just keeps presenting the login screen.

**Comment by Tigger1** [comment]
Hello dmjjmd,

thank you for sharing your problem with us and the feedback.

I can recommend you the same process as in BaronosMS' case. Please, restart the Arizen wallet and if it doesn't help, restart even the PC. 

We know about this bug and we've been still solving this issue as hard as we can.

May I ask you for sharing with us which operating system you use, please? Thank you in advance.

Happy holidays,
Tigger1

**Comment by dmjjmd** [comment]
Hi - thanks for the quick reply.  I followed the suggested approach, restarted my PC and the wallet.  The same issue happened, but I found if I just re-entered the username and password multiple times (at least 7+) it did eventually let me into the wallet, so similar results to BaronosMS.  I'm running the wallet on a Windows 10 VM (version 10.0.15063 build 15063)

**Comment by woky** [comment]
@BaronosMS @dmjjmd which version of Arizen are you using?

**Comment by dmjjmd** [comment]
@woky  I'm using Arizen version 1.1.1, which I believe is the latest.  This was the first version I installed so not an upgrade from a previous version.  Also, when I put in the correct username and password, it never says "wrong username or password", it just clears my entry and shows the same page asking for username and password.

**Comment by alvarocobarro** [comment]
Hi! I ve the same problem, but im working with mac. Im sure that im writing perfectly my username and my password and i cant login to my arizen wallet. There is someone that can help us?

**Comment by woky** [comment]
The issue is fixed in PR #165. Wait for next version please.

**Comment by zhangweidai** [comment]
Hi, I'm having trouble logging in.  I only ever have a few passwords, and they aren't working.  Is there anything you can do to help me?  I didn't have a chance to backup, and I have tried restarting the wallet and PC.  I'm running Windows 10.

**Comment by sirbupsalot** [comment]
Hi, I also cannot login to the Arizen wallet. I am using version 1.1.1 on mac and have tried closing and restarting the app and my computer 20+ times. As dmjjmd said, 'when I put in the correct username and password, it never says "wrong username or password", it just clears my entry and shows the same page asking for username and password.' Please advise.

**Comment by dmjjmd** [comment]
@zhangweidai @sirbupsalot it looks like they have this fixed in an upcoming version, but until then, I was able to get logged into my wallet by entering the correct username and password 5-7 times.  It doesn't look like it will work but keep trying and it will hopefully eventually let you in.

**Comment by zhangweidai** [comment]
As another person stated previously, I'm at 20 or more attempts and fairly
confidant in my password with still no luck.

**Comment by alvarocobarro** [comment]
The bug isnt fixed...

**Comment by zhangweidai** [comment]
Hi, ok looks like I had also forgot my password. Found it on my desktop and
now after 5 correct password attempts I'm in. Wow.  Zencash to the moon!

**Comment by LukasBures** [comment]
The issue has been fixed in PR #165. Wait for next release v1.1.2

**Comment by sirbupsalot** [comment]
@LukasBures Any idea when this release will be?

**Comment by LukasBures** [comment]
Around 14th January.

**Comment by sirbupsalot** [comment]
Thank you @LukasBures.

**Comment by sirbupsalot** [comment]
Hi @LukasBures, I have downloaded the latest release, unfortunately I still cannot login to my wallet. What do you recommend?

**Comment by woky** [comment]
@sirbupsalot Would you please send me a screenshot?

**Comment by woky** [comment]
@sirbupsalot Well, it really looks like you're entering incorrect credentials now. The previous issue was that you didn't even get warning when the page was cleared but now I see that you're being informed of incorrect credentials.

I don't really have time for this now, but in the following days, I could make a command line utility that will allow you to extract keys from the encrypted DB. I'm sure it'd be useful for more cases. In your case we could rule out the possibility that there's an issue in the Electron code (or find out that there is). I'll get back soon.

**Comment by sirbupsalot** [comment]
@woky Thanks very much for your response, if it helps I have a screenshot of the address where the ZEN was sent. Thanks again.

**Comment by Dionesjk** [comment]
I'm having the same problem. After the new version 1.1.3 appeared. Had logged the last time 19/01 successfully. Now 21/01 was login wrong username or passoword appears. I am sure the password and the user are correct. I made several attempts even,  including on a different computer and could not. What should I do?

**Comment by skilletxt** [comment]
I am having the same issue as Dionsjk. I was able to log in fine a few days ago. I went to log in today, saw an update and now it says wrong password. I have done everything listed above several times. Is there any new advise? iIwould really like to get this sorted out...

**Comment by gsfakianakis** [comment]
What is your OS ?

**Comment by gsfakianakis** [comment]
Could you try these ?
1. In your current pc make a new account and after you create it, try to login to the new account.
2. go to ~/.arizen/wallets and backup the username.awd file. If possible go to another PC copy your username.awd file in the ~/.arizen/wallets, open arizen  and try to login from there, using the same credentials.
3. Having your wallet backed up. Uninstall arizen, download again from github and verify the sha256 sum. If the sum is correct, install arizen and try to login again.

~/.arizen/wallets  for windows is : %appdata%\Arizen\wallets
Download in : https://github.com/ZencashOfficial/arizen/releases

**Comment by skilletxt** [comment]
Got it working! It was my dumb fault.... I just wanted to let you know. Thanks for the quick response!

**Comment by gsfakianakis** [comment]
@skilletxt What was the problem finally ? Did you download the arizen wallet again ?

**Comment by sirbupsalot** [comment]
@gsfakianakis I use mac and still cannot login. I have created a dummy wallet and can access it without any problem. As I mentioned above, if it helps I have a screenshot of the address where the ZEN was received.

**Comment by gsfakianakis** [comment]
Could you go to ~/.arizen/wallets and backup the username.awd file ?

Then uninstall arizen, download again from github and verify the sha256 sum. If the sum is correct, install arizen and try to login again.

Let us know if it works.

**Comment by sirbupsalot** [comment]
I'm using Mac, searching ~/.arizen/wallets in finder returns nothing. Apologies, but I don't know where the wallet is actually saved.

**Comment by gsfakianakis** [comment]
For mac it should be here:

Users/<username>/Library/Application Support/Arizen

**Comment by gsfakianakis** [comment]
No.
It should be 

C:\Users\Diones\AppData\Roaming\Arizen\wallets

or %appdata%\Arizen\wallets

**Comment by Dionesjk** [comment]
I found the username.awd file. 
I went on another computer, paste the file in \Arizen\wallets, tried to login with the user and I could not. I entered another arizen wallet and went to file> import Encrypted arizen wallet,  but could not import the wallet. This error appears
https://i.imgur.com/YDItUg9.png

**Comment by gsfakianakis** [comment]
Backup the username.awd in another location
and
In your current pc make a new test account and after you create it, try to login to the new account.

**Comment by sirbupsalot** [comment]
@gsfakianakis I have done as you suggested below and unfortunately I still cannot login, I get the "Wrong username or password" message. I can however login to the dummy wallet I created to test. Do you have any further recommendations for me? Thanks for your prompt support so far.


Could you go to ~/.arizen/wallets and backup the username.awd file ?

Then uninstall arizen, download again from github and verify the sha256 sum. If the sum is correct, install arizen and try to login again.

Let us know if it works.

**Comment by gsfakianakis** [comment]
@sirbupsalot 
Did you downloaded by yourself the arizen from github ?
if no, please try this.
if yes then that means that either you use wrong password or the file is corrupted.

Rename the username.awd to username-latest.awd and keep it backed up somewhere.

Now go to .../arizen/wallets/backups and you should see a lot of files in this format:

username-xxxxxxxxxxxxxx.awd (ex. username-20180113162435.awd)
This is date and time. Copy the latest date file in the  .../arizen/wallets and rename it username.awd.
Then Restart arizen and try to login again.

Do this for the next files also.

**Comment by woky** [comment]
Linux/Mac users try the following. You need latest node.js, npm (or yarn) and unzip (may differ on Mac).

    wget https://gist.github.com/woky/5c00cd2436fbece228116a5dd65313fe/archive/6c9921a64ec69e16afc229ef1ea9e8cab1b61d00.zip
    unzip 6c9921a64ec69e16afc229ef1ea9e8cab1b61d00.zip
    cd 6c9921a64ec69e16afc229ef1ea9e8cab1b61d00
    npm install # or yarn
    node index.js /path/to/wallets/wallet_username.awd wallet_username password

The last command will output private keys and addresses if you enter correct password. The path to the awd file is

- Linux: `~/.arizen/wallets/wallet_username.awd`
- Windows: `C:\Users\username\AppData\Roaming\Arizen\wallets\wallet_username.awd`
- Mac: `/Users/username/Library/Application Support/Arizen/wallet_username.awd`

**Comment by woky** [comment]
@phdacademy You need to run `npm install` or `yarn` first.

**Comment by LukasBures** [comment]
Any update here? Can I close it?

**Comment by phdacademy** [comment]
Yes, there is an update:  
Restarting my Mac and trying my password again caused the wallet to open.  Please close this, and my apologies for not staying on top of this.

**Comment by LukasBures** [comment]
ok, thank you

**Comment by gsfakianakis** [comment]
@BigMank 
Go to the wallet folder and check if you see if your_username.awd wallet is there.

The path to the awd file is

Linux: ~/.arizen/wallets/wallet_username.awd
Windows: C:\Users\username\AppData\Roaming\Arizen\wallets\wallet_username.awd
Mac: /Users/username/Library/Application Support/Arizen/wallet_username.awd

**Comment by BigMank** [comment]
Its there. Looks like it has multiple back up files to. Last modified was 6/3/18 at 12 AM.

**Comment by gsfakianakis** [comment]
Rename the file username.awd to  username-latest-backup.awd  Take the latest backup and rename it username.awd. Then try to login again. If you succeed login in, make sure that the backup contains all your addresses.

**Comment by BigMank** [comment]
Still same error message

**Comment by gsfakianakis** [comment]
Then backup your wallet, uninstall v117 and install v1.1.6, and try again.

**Comment by BigMank** [comment]
Ok I will try that. Curios, Why cant I see the appdata folder without searching in windows  %appdata%?

**Comment by BigMank** [comment]
gsfakianakis you are a gifted genius! Thank you so much!

This worked:
Rename the file username.awd to username-latest-backup.awd Take the latest backup and rename it username.awd. Then try to login again. If you succeed login in, make sure that the backup contains all your addresses.

**Comment by gsfakianakis** [comment]
Nice. Was that with v1.1.7 ?

**Comment by BigMank** [comment]
I did download and reinstall v1.1.7 and had the error message. I then did the rename wallet  which didnt work. I restarted my computer and tried to log in again and that worked, keep in mind I did rename the wallet before restarting.
thanks again

**Comment by milyway** [comment]
Hi,

I have Arizen v1.1.8 on windows 7, 

Yesterday everything worked fine., But today I can't log in . 
It keeps saying that I have wrong wallet name or password, which is not that case.
I've tried to download again form Github and reinstall, did not work.
and I've tried to do other methods written above, but can't find wallet_username.awd, may be it's different for v1.1.8 ?

I'd greatly appreciate your help.
Thank you.

**Comment by Tigger1** [comment]
Hi @milyway ,

thank you for using GitHub. I had a problem find this topic because it's closed. You could use a new one and just tag this topic.

If I understand correctly you want to know where is your last backup *.awd file stored?

Tigger1

**Comment by milyway** [comment]
Hi, Tigger1

I just need to log in to Arizen.
Any fix would be appreciated. 

Thank you.

**Comment by varu33** [comment]
Who pays for lost accounts??? So you do not see that for a long time from one version to another no one fixes the bug trying this one tries this but without any result it is not normal for someone not to answer it and resolve the problem people lost every day money shut down the f.k.n.g wallet!!! version V9.9.9.9.9 and dont work!!!!!!!!!!!!!!!!!!

**Comment by FakeTive** [comment]
Guys,
Same here:
99.9% sure that the password is correct (twice re-logged in after creating the wallet), loosing my mind actually.
Windows 7
v1.1.8 (innitially was this version, I also tried installing 1.1.7)
Manualy backed up once

Tried everything:
- installing v.1.1.7
- reopening
- rebooting
- reinstalling
- creating a new wallet and trying to restore from back-up
- restoring from automatic variouse backups.

would really appreciate any usefull info.

**Comment by LukasBures** [comment]
@milyway @varu33 @FakeTive 

I have added multiple checks to this issue, you can see them here (will be included in v1.1.9): bf016216ab12808388cf15678706ab32124aa0ca

All that I can tell you is:
1) you have wrong wallet name or password (if that is not your case) –>
2) your file is corrupted and can't be decrypted at all (that probably has happened due to a system crash / blue screen / alt+F4 / or similar) -> then you need to use your backups for accessing your funds. There isn't any way how can I help you more.

In v1.1.9 please check which warning you will get:
1) Probably corrupted wallet file or wrong wallet name or password -> corrupted wallet file
2) Wrong wallet name or password –> wrong credentials
3) Wallet with this name does NOT exist –> bad wallet name and/or wallet file doesn't exist

**Comment by FakeTive** [comment]
@LukasBures 
Thank you for the reply.
So if I have a wrong password that means that I've consequentrly entered same wrong password 3 times.
If backups are corrupt they must be corrupt each an everyone (7-8 backs)

I'm now starting to think on how to check typos in my password and maybe bruteforce with a list of possible variants. It's like couple of millions. Would I be blocked or something?

**Comment by SmoothLuke** [comment]
hi Lukas Bures I'm using the 1.1.9. and am receiving the message "Probably corrupted wallet file or wrong wallet name or password -> corrupted wallet file" to confirm this means I have lost my my access to my wallet and the contents that were within?

**Comment by FakeTive** [comment]
@LukasBures 
So, I've installed 1.1.9 and the error is now "Probably corrupted wallet file or wrong wallet name or password"
What's the help of that? I though I would at least know what type of trouble I'm in. 
Is there a way to know if the wallet is corrupted OR credantials are wrong?

**Comment by LukasBures** [comment]
@FakeTive sorry there is no way how to know if the wallet is corrupted OR credentials are wrong because the return message of the used library for decrypting doesn't say more. If you have backups, try to recover. If you are sure, that your wallet name and password is correct, then I have heard that somebody was trying to input it many times 15-20x and then the wallet lets him/her login (but this is the really strange approach, but worth to try). I don't know in which state is your computer (bad HDD sector, your antivirus deleted part of Arizen files, and or etc ... ).

**Comment by LukasBures** [comment]
@cryptostevo - check your settings and uncheck/disallow "domain fronting" and check API servers - if there is not a misspelling issue and save, log out and check if your "update" circle is still spinning.

**Comment by FakeTive** [comment]
@LukasBures
Can you recomment how to be 100% sure that this will never happen again?
We are looking at a service based on Zen, but this experience and trace of all those people lost their wallets doesn't encourage much.

**Comment by LukasBures** [comment]
@FakeTive I can give you my recommendation:
1) generate as many addresses you will need ... eg 100 - 1000 or how many you want
2) copy that wallet to the 2nd computer (at least) and run it there too
3) export and backup private keys (cold USB storage)
4) NEVER create next address just use that generated one
5) backup your backups on regularly basis

That is what I personally use.

BTW - I use MacOS and I have not been experienced with your issue ...

**Comment by FakeTive** [comment]
@LukasBures
"NEVER create next address just use that generated one"
Could you please explain?

**Comment by LukasBures** [comment]
@FakeTive because when you have your wallet on 2 and more PCs then one address which you create in one wallet won't be in the second wallet included. And because you wont have that address included in previous backups.

**Comment by zennermac** [comment]
I am closing this out now as it seems to have been answered fairly completely.

**Comment by derb540** [comment]
Can't log in to Arizen wallet, been trying for 2 days now any help would be appreciated.
I enter user name, password and nothing happens.

**Comment by zennermac** [comment]
Just replying that we addressed @derb540 via our helpdesk for the duplicate issue https://github.com/ZencashOfficial/arizen/issues/431
