### ISSUE TITLE
Win wallet moved to Ubuntu

### ISSUE THREAD

**Issue by 300cpilot** [ZencashOfficial/arizen#389]
**Describe the bug**
On version 1.2.0 (Latest) and what I am trying to do is to put a copy of my Win10 wallet on a linux Mint 19 machine. The wallet will import but will never update beyond the point it was imported.

**To Reproduce**
1. Backup the wallet and save to thumb drive.
2. Create new wallet with exact same username/password.
3. Then Import the wallet from the thumb drive on the linux machine.
4. Remove connection to securenode that was restored from backup.
5. Have tried with and without the securenode connection.
6. Have also created a new wallet and imported the private keys. After 4 days it still had not synced and will not update. Reads 0 zen.

**Expected behavior**
Expected to work, I use this on several machines and it runs fine. But moving wallets seams to be a challenge.
**Screenshots**
the little wheel just goes around.

**Please complete the following information:**
 - OS: Linux Mint 19, updated
 - OS: Backup made on - Windows 10 pro current udates applied
 - Arizen Version [ 1.2]
 - Dell e7250 laptop, 16 gigs ram

**Additional context**
This behavior is reproduceable in a virtualbox vm as well on a Win 10 host. Have also removed the firewall on the computer that I am trying to use.

**Comment by 300cpilot** [comment]
This has to do with the whole disk encryption in Ubuntu/Mint. When the same device is not encrypted it works fine. This was reproduced on two different laptops.

**Comment by zennermac** [comment]
Hi there

I would encourage you to try yesterdays maintenance release, this could be related to some intermittent transaction processing problems which are now fixed.

**Comment by zennermac** [comment]
https://github.com/ZencashOfficial/arizen/releases/tag/v1.2.3

**Comment by 300cpilot** [comment]
Sorry for the late reply. This did not resolve the issue. Still does not allow updates on Linux Mint with drive encryption enabled. I will watch and try the next updates.

**Comment by zennermac** [comment]
@vherus can we test this together as I cannot replicate

**Comment by Angelika1920** [comment]
God

**Comment by cronicc** [comment]
Unable to replicate issue. Arizen is in pure maintenance mode, no new features will be implemented. Only critical bug fixes and dependency management are being done.
